package api

import (
	"io/fs"
	"net/http"
)

// NewRouter builds the full UMMarr web UI + HTTP API using stdlib
// http.ServeMux's method+path patterns - no router dependency, matching
// this project's minimal-dependency pattern throughout every prior pass.
func NewRouter(deps Deps) http.Handler {
	h := &handler{deps: deps, pages: parsePages(), partials: parsePartials(), loginPage: parseLoginPage()}
	mux := http.NewServeMux()

	mux.HandleFunc("GET /login", h.Login)
	mux.HandleFunc("POST /login", h.LoginSubmit)
	mux.HandleFunc("POST /logout", h.Logout)

	// staticFS embeds paths as "static/htmx.min.js" etc (the embed
	// directive's own path prefix) - fs.Sub re-roots it so a request for
	// "/static/htmx.min.js" resolves to "htmx.min.js" inside the FS, not
	// "static/htmx.min.js" again.
	staticSub, err := fs.Sub(staticFS, "static")
	if err != nil {
		panic(err) // embed.FS with a fixed, compile-time-verified path - can't actually fail
	}
	mux.Handle("GET /static/", http.StripPrefix("/static/", http.FileServerFS(staticSub)))

	mux.HandleFunc("GET /{$}", h.Home)

	mux.HandleFunc("GET /movies", h.Movies)
	mux.HandleFunc("GET /movies/search", h.MovieSearch)
	mux.HandleFunc("POST /movies/add", h.MovieAdd)
	mux.HandleFunc("GET /movies/{id}", h.MovieDetail)
	mux.HandleFunc("GET /movies/{id}/releases", h.MovieReleases)
	mux.HandleFunc("POST /movies/{id}/grab", h.MovieGrab)
	mux.HandleFunc("POST /movies/{id}/search", h.MovieAutoSearch)
	mux.HandleFunc("GET /movies/{id}/fix-match", h.MovieFixMatch)
	mux.HandleFunc("POST /movies/{id}/fix-match", h.MovieFixMatchApply)
	mux.HandleFunc("POST /movies/search-missing", h.StartMissingSearch)
	mux.HandleFunc("GET /movies/search-missing", h.MissingSearchStatus)
	mux.HandleFunc("POST /movies/search-cutoff", h.StartMissingSearch)
	mux.HandleFunc("GET /movies/search-cutoff", h.MissingSearchStatus)
	mux.HandleFunc("POST /movies/{id}/refresh", h.MovieRefresh)
	mux.HandleFunc("POST /movies/{id}/monitored", h.MovieMonitoredToggle)

	mux.HandleFunc("GET /tv", h.Series)
	mux.HandleFunc("GET /tv/search", h.SeriesSearch)
	mux.HandleFunc("POST /tv/add", h.SeriesAdd)
	mux.HandleFunc("GET /tv/{id}", h.SeriesDetail)
	mux.HandleFunc("GET /tv/{id}/releases", h.SeriesReleases)
	mux.HandleFunc("POST /tv/{id}/grab", h.SeriesGrab)
	mux.HandleFunc("POST /tv/{id}/search", h.SeriesAutoSearch)
	mux.HandleFunc("GET /tv/{id}/fix-match", h.SeriesFixMatch)
	mux.HandleFunc("POST /tv/{id}/fix-match", h.SeriesFixMatchApply)
	mux.HandleFunc("POST /tv/{id}/seasons/{season}/search", h.SeasonAutoSearch)
	mux.HandleFunc("POST /tv/{id}/seasons/{season}/episode-names", h.SeasonEpisodeNames)
	mux.HandleFunc("POST /tv/{id}/episode-names", h.SeasonEpisodeNames)
	mux.HandleFunc("POST /tv/{id}/episodes/{episodeId}/search", h.EpisodeAutoSearch)
	mux.HandleFunc("POST /tv/search-missing", h.StartMissingSearch)
	mux.HandleFunc("GET /tv/search-missing", h.MissingSearchStatus)
	mux.HandleFunc("POST /tv/search-cutoff", h.StartMissingSearch)
	mux.HandleFunc("GET /tv/search-cutoff", h.MissingSearchStatus)
	mux.HandleFunc("POST /tv/{id}/refresh", h.SeriesRefresh)
	mux.HandleFunc("POST /movies/editor", h.MoviesEditorSave)
	mux.HandleFunc("POST /movies/editor/delete", h.MoviesEditorDelete)
	mux.HandleFunc("POST /movies/editor/search", h.LibraryEditorSearch)
	mux.HandleFunc("POST /tv/editor", h.SeriesEditorSave)
	mux.HandleFunc("POST /tv/editor/delete", h.SeriesEditorDelete)
	mux.HandleFunc("POST /tv/editor/search", h.LibraryEditorSearch)
	mux.HandleFunc("POST /tv/editor/monitor", h.SeriesEditorMonitor)
	mux.HandleFunc("GET /tv/seasonpass", h.SeasonPass)
	mux.HandleFunc("POST /tv/seasonpass", h.SeasonPassSave)
	mux.HandleFunc("POST /tv/seasonpass/toggle", h.SeasonPassToggle)
	mux.HandleFunc("POST /settings/media-management/plex-media-info/test", h.TestPlexMediaInfo)
	mux.HandleFunc("GET /tv/{id}/rename-preview", h.SeriesRenamePreview)
	mux.HandleFunc("POST /tv/{id}/rename", h.SeriesRenameFiles)
	mux.HandleFunc("DELETE /tv/{id}", h.SeriesDelete)
	mux.HandleFunc("GET /tv/{id}/delete", h.SeriesDeleteForm)
	mux.HandleFunc("GET /tv/{id}/edit", h.SeriesEditForm)
	mux.HandleFunc("POST /tv/{id}/edit", h.SeriesEditSave)
	mux.HandleFunc("GET /tv/{id}/monitor", h.SeriesMonitorForm)
	mux.HandleFunc("POST /tv/{id}/monitor", h.SeriesMonitorApply)
	mux.HandleFunc("GET /tv/{id}/manage-episodes", h.SeriesManageEpisodesForm)
	mux.HandleFunc("POST /tv/{id}/manage-episodes/delete", h.SeriesDeleteEpisodeFiles)
	mux.HandleFunc("POST /tv/{id}/manage-episodes", h.SeriesManageEpisodesImport)
	mux.HandleFunc("POST /tv/{id}/monitored", h.SeriesMonitoredToggle)
	mux.HandleFunc("POST /tv/{id}/seasons/{season}/monitored", h.SeasonMonitoredToggle)
	mux.HandleFunc("GET /tv/{id}/episodes/status", h.SeriesEpisodeStatuses)
	mux.HandleFunc("GET /tv/{id}/episodes/{episodeId}", h.EpisodeDetails)
	mux.HandleFunc("GET /tv/{id}/episodes/{episodeId}/releases", h.EpisodeReleases)
	mux.HandleFunc("POST /tv/{id}/episodes/{episodeId}/grab", h.EpisodeGrab)
	mux.HandleFunc("POST /tv/{id}/episodes/{episodeId}/monitored", h.EpisodeMonitoredToggle)

	mux.HandleFunc("GET /music", h.Music)
	mux.HandleFunc("GET /music/search", h.MusicSearch)
	mux.HandleFunc("GET /music/artists/{id}", h.ArtistDetail)
	mux.HandleFunc("POST /music/artists/{id}/refresh", h.ArtistRefresh)
	mux.HandleFunc("POST /music/artists/{id}/search", h.ArtistSearch)
	mux.HandleFunc("POST /music/artists/{id}/monitored", h.ArtistMonitoredToggle)
	mux.HandleFunc("GET /music/artists/{id}/edit", h.ArtistEditForm)
	mux.HandleFunc("POST /music/artists/{id}/edit", h.ArtistEditSave)
	mux.HandleFunc("GET /music/artists/{id}/delete", h.ArtistDeleteForm)
	mux.HandleFunc("DELETE /music/artists/{id}", h.ArtistDelete)
	mux.HandleFunc("GET /music/artists/{id}/metadata", h.ArtistMetadata)
	mux.HandleFunc("GET /music/artists/{id}/rename-preview", h.ArtistRenamePreview)
	mux.HandleFunc("POST /music/artists/{id}/rename", h.ArtistRenameFiles)
	mux.HandleFunc("GET /music/artists/{id}/monitor", h.ArtistMonitorForm)
	mux.HandleFunc("POST /music/artists/{id}/monitor", h.ArtistMonitorApply)
	mux.HandleFunc("POST /music/editor", h.MusicEditorSave)
	mux.HandleFunc("POST /music/editor/delete", h.MusicEditorDelete)
	mux.HandleFunc("POST /music/editor/search", h.MusicEditorSearch)
	mux.HandleFunc("POST /music/editor/monitor", h.MusicEditorMonitor)
	mux.HandleFunc("GET /music/albumpass", h.AlbumPass)
	mux.HandleFunc("POST /music/albumpass", h.AlbumPassSave)
	mux.HandleFunc("POST /music/albumpass/toggle", h.AlbumPassToggle)
	mux.HandleFunc("GET /music/artists/{id}/albums/status", h.ArtistAlbumStatuses)
	mux.HandleFunc("GET /music/artists/{id}/albums", h.MusicArtistAlbums)
	mux.HandleFunc("GET /music/artists/{id}/fix-match", h.ArtistFixMatch)
	mux.HandleFunc("POST /music/artists/{id}/fix-match", h.ArtistFixMatchApply)
	mux.HandleFunc("GET /music/albums/{id}/fix-match", h.AlbumFixMatch)
	mux.HandleFunc("POST /music/albums/{id}/fix-match", h.AlbumFixMatchApply)
	mux.HandleFunc("POST /music/add-artist", h.MusicArtistAdd)
	mux.HandleFunc("POST /music/add-album", h.MusicAlbumAdd)
	mux.HandleFunc("GET /music/albums/{id}", h.AlbumDetail)
	mux.HandleFunc("GET /music/albums/{artist}/{album}", h.AlbumDetail)
	mux.HandleFunc("GET /music/albums/{id}/rename-preview", h.AlbumRenamePreview)
	mux.HandleFunc("POST /music/albums/{id}/rename", h.AlbumRenameFiles)
	mux.HandleFunc("GET /music/albums/{id}/edit", h.AlbumEditForm)
	mux.HandleFunc("POST /music/albums/{id}/edit", h.AlbumEditSave)
	mux.HandleFunc("GET /music/albums/{id}/delete", h.AlbumDeleteForm)
	mux.HandleFunc("DELETE /music/albums/{id}", h.AlbumDelete)
	mux.HandleFunc("GET /music/albums/{id}/releases", h.AlbumReleases)
	mux.HandleFunc("POST /music/albums/{id}/grab", h.AlbumGrab)
	mux.HandleFunc("POST /music/albums/{id}/search", h.AlbumAutoSearch)
	mux.HandleFunc("POST /music/search-missing", h.StartMissingSearch)
	mux.HandleFunc("GET /music/search-missing", h.MissingSearchStatus)
	mux.HandleFunc("POST /music/search-cutoff", h.StartMissingSearch)
	mux.HandleFunc("GET /music/search-cutoff", h.MissingSearchStatus)
	mux.HandleFunc("POST /music/albums/{id}/monitored", h.AlbumMonitoredToggle)
	mux.HandleFunc("GET /music/albums/{id}/manage-tracks", h.AlbumManageTracksForm)
	mux.HandleFunc("POST /music/albums/{id}/manage-tracks", h.AlbumManageTracksApply)
	mux.HandleFunc("POST /music/albums/{id}/manage-tracks/delete", h.AlbumDeleteTrackFiles)
	mux.HandleFunc("GET /music/albums/{id}/tracks/status", h.AlbumTrackStatuses)
	mux.HandleFunc("GET /music/albums/{id}/tracks/{trackId}/releases", h.TrackReleases)
	mux.HandleFunc("POST /music/albums/{id}/tracks/{trackId}/grab", h.TrackGrab)

	mux.HandleFunc("GET /activity", h.Activity)
	mux.HandleFunc("GET /history", h.History)
	mux.HandleFunc("GET /system", h.System)
	mux.HandleFunc("GET /system/{tab}", h.System)
	mux.HandleFunc("POST /system/tasks/{name}/run", h.RunTask)
	mux.HandleFunc("POST /system/backups", h.CreateBackup)
	mux.HandleFunc("GET /system/backups/{name}/download", h.DownloadBackup)
	mux.HandleFunc("POST /system/backups/{name}/restore", h.RestoreBackup)
	mux.HandleFunc("DELETE /system/backups/{name}", h.DeleteBackup)
	mux.HandleFunc("POST /system/updates/check", h.CheckUpdates)
	mux.HandleFunc("GET /activity/queue", h.ActivityQueue)
	mux.HandleFunc("POST /activity/grabs/{id}/retry", h.RetryGrab)
	mux.HandleFunc("POST /activity/grabs/{id}/remove", h.RemoveGrab)
	mux.HandleFunc("GET /activity/blocklist", h.ActivityBlocklist)
	mux.HandleFunc("DELETE /activity/blocklist/{id}", h.DeleteBlocklistEntry)
	mux.HandleFunc("POST /activity/blocklist/clear", h.ClearBlocklist)
	mux.HandleFunc("GET /activity/manual-import", h.ManualImport)
	mux.HandleFunc("POST /activity/manual-import", h.ManualImportSubmit)
	mux.HandleFunc("GET /activity/manual-import/tracks", h.ManualImportTracks)

	mux.HandleFunc("POST /downloads/{hash}/completed", h.DownloadCompleted)

	mux.HandleFunc("GET /settings", h.Settings)
	mux.HandleFunc("GET /settings/{tab}", h.Settings)
	mux.HandleFunc("POST /settings/root-folders", h.CreateRootFolder)
	mux.HandleFunc("DELETE /settings/root-folders/{id}", h.DeleteRootFolder)
	mux.HandleFunc("POST /settings/quality-profiles", h.CreateQualityProfile)
	mux.HandleFunc("GET /settings/quality-profiles/{id}", h.QualityProfileEdit)
	mux.HandleFunc("POST /settings/quality-profiles/{id}/items", h.UpdateQualityProfileItems)
	mux.HandleFunc("POST /settings/quality-profiles/{id}/default", h.SetDefaultQualityProfile)
	mux.HandleFunc("POST /settings/preferred-words", h.CreatePreferredWord)
	mux.HandleFunc("POST /settings/preferred-words/{id}", h.UpdatePreferredWord)
	mux.HandleFunc("DELETE /settings/preferred-words/{id}", h.DeletePreferredWord)
	mux.HandleFunc("POST /settings/account", h.UpdateAccount)
	mux.HandleFunc("POST /settings/host", h.UpdateHostSettings)
	mux.HandleFunc("POST /settings/metadata", h.UpdateMetadataSettings)
	mux.HandleFunc("POST /settings/metadata-sources/move", h.MoveMetadataSource)
	mux.HandleFunc("GET /settings/metadata-sources/new", h.NewMetadataProviderForm)
	mux.HandleFunc("POST /settings/metadata-sources", h.SaveMetadataProvider)
	mux.HandleFunc("GET /settings/metadata-sources/{id}/edit", h.EditMetadataProviderForm)
	mux.HandleFunc("DELETE /settings/metadata-sources/{id}", h.DeleteMetadataProvider)
	mux.HandleFunc("GET /settings/custom-formats/new", h.NewCustomFormatForm)
	mux.HandleFunc("GET /settings/custom-formats/condition", h.CustomFormatConditionRow)
	mux.HandleFunc("GET /settings/custom-formats/export", h.ExportCustomFormats)
	mux.HandleFunc("POST /settings/custom-formats/import", h.ImportCustomFormats)
	mux.HandleFunc("POST /settings/custom-formats", h.SaveCustomFormat)
	mux.HandleFunc("GET /settings/custom-formats/{id}/edit", h.EditCustomFormatForm)
	mux.HandleFunc("DELETE /settings/custom-formats/{id}", h.DeleteCustomFormat)
	mux.HandleFunc("GET /movies/{id}/metadata", h.MovieMetadata)
	mux.HandleFunc("POST /metadata/{type}/{id}/poster", h.ChoosePoster)
	mux.HandleFunc("POST /movies/{id}/refresh-metadata", h.MovieRefreshMetadata)
	mux.HandleFunc("GET /tv/{id}/metadata", h.SeriesMetadata)
	mux.HandleFunc("GET /music/albums/{id}/metadata", h.AlbumMetadata)
	mux.HandleFunc("POST /music/albums/{id}/refresh-metadata", h.AlbumRefreshMetadata)
	mux.HandleFunc("GET /settings/import-lists/new", h.NewImportListForm)
	mux.HandleFunc("POST /settings/import-lists", h.CreateImportList)
	mux.HandleFunc("POST /settings/import-lists/test", h.TestImportList)
	mux.HandleFunc("POST /settings/import-lists/sync", h.SyncImportLists)
	mux.HandleFunc("POST /settings/import-lists/exclusions", h.AddExclusion)
	mux.HandleFunc("DELETE /settings/import-lists/exclusions/{id}", h.DeleteExclusion)
	mux.HandleFunc("GET /settings/import-lists/{id}/edit", h.EditImportListForm)
	mux.HandleFunc("POST /settings/import-lists/{id}", h.UpdateImportList)
	mux.HandleFunc("DELETE /settings/import-lists/{id}", h.DeleteImportList)
	mux.HandleFunc("GET /settings/indexers/new", h.NewIndexerForm)
	mux.HandleFunc("POST /settings/indexers", h.CreateIndexer)
	mux.HandleFunc("POST /settings/indexers/test", h.TestIndexer)
	mux.HandleFunc("POST /settings/indexers/test-all", h.TestAllIndexers)
	mux.HandleFunc("POST /settings/indexers/bulk", h.BulkEditIndexers)
	mux.HandleFunc("POST /settings/indexers/options", h.UpdateIndexerOptions)
	mux.HandleFunc("POST /settings/indexers/rss-sync", h.RunRSSSync)
	mux.HandleFunc("GET /settings/api-key", h.ShowAPIKey)
	mux.HandleFunc("POST /settings/api-key/regenerate", h.RegenerateAPIKey)

	// Radarr-compatible API for Prowlarr's app sync (see arr_api.go).
	mux.HandleFunc("GET /api/v3/system/status", h.arrAPI(h.ArrSystemStatus))
	mux.HandleFunc("GET /api/v3/indexer", h.arrAPI(h.ArrListIndexers))
	mux.HandleFunc("GET /api/v3/indexer/schema", h.arrAPI(h.ArrIndexerSchema))
	mux.HandleFunc("POST /api/v3/indexer/test", h.arrAPI(h.ArrTestIndexer))
	mux.HandleFunc("GET /api/v3/indexer/{id}", h.arrAPI(h.ArrGetIndexer))
	mux.HandleFunc("POST /api/v3/indexer", h.arrAPI(h.ArrCreateIndexer))
	mux.HandleFunc("PUT /api/v3/indexer/{id}", h.arrAPI(h.ArrUpdateIndexer))
	mux.HandleFunc("DELETE /api/v3/indexer/{id}", h.arrAPI(h.ArrDeleteIndexer))
	mux.HandleFunc("GET /api", h.ApiDocs)
	mux.HandleFunc("GET /api/v3/movie", h.arrAPI(h.ApiListMovies))
	mux.HandleFunc("GET /api/v3/movie/lookup", h.arrAPI(h.ApiLookupMovie))
	mux.HandleFunc("GET /api/v3/movie/{id}", h.arrAPI(h.ApiGetMovie))
	mux.HandleFunc("POST /api/v3/movie", h.arrAPI(h.ApiAddMovie))
	mux.HandleFunc("PUT /api/v3/movie/{id}", h.arrAPI(h.ApiUpdateMovie))
	mux.HandleFunc("DELETE /api/v3/movie/{id}", h.arrAPI(h.ApiDeleteMovie))
	mux.HandleFunc("GET /api/v3/series", h.arrAPI(h.ApiListSeries))
	mux.HandleFunc("GET /api/v3/series/lookup", h.arrAPI(h.ApiLookupSeries))
	mux.HandleFunc("GET /api/v3/series/{id}", h.arrAPI(h.ApiGetSeries))
	mux.HandleFunc("POST /api/v3/series", h.arrAPI(h.ApiAddSeries))
	mux.HandleFunc("PUT /api/v3/series/{id}", h.arrAPI(h.ApiUpdateSeries))
	mux.HandleFunc("DELETE /api/v3/series/{id}", h.arrAPI(h.ApiDeleteSeries))
	mux.HandleFunc("GET /api/v3/episode", h.arrAPI(h.ApiListEpisodes))
	mux.HandleFunc("PUT /api/v3/episode/{id}", h.arrAPI(h.ApiUpdateEpisode))
	mux.HandleFunc("GET /api/v3/artist", h.arrAPI(h.ApiListArtists))
	mux.HandleFunc("GET /api/v3/artist/lookup", h.arrAPI(h.ApiLookupArtist))
	mux.HandleFunc("POST /api/v3/artist", h.arrAPI(h.ApiAddArtist))
	mux.HandleFunc("GET /api/v3/album", h.arrAPI(h.ApiListAlbums))
	mux.HandleFunc("GET /api/v3/album/{id}", h.arrAPI(h.ApiGetAlbum))
	mux.HandleFunc("POST /api/v3/album", h.arrAPI(h.ApiAddAlbum))
	mux.HandleFunc("PUT /api/v3/album/{id}", h.arrAPI(h.ApiUpdateAlbum))
	mux.HandleFunc("DELETE /api/v3/album/{id}", h.arrAPI(h.ApiDeleteAlbum))
	mux.HandleFunc("GET /api/v3/queue", h.arrAPI(h.ApiQueue))
	mux.HandleFunc("DELETE /api/v3/queue/{id}", h.arrAPI(h.ApiQueueDelete))
	mux.HandleFunc("GET /api/v3/blocklist", h.arrAPI(h.ApiBlocklist))
	mux.HandleFunc("DELETE /api/v3/blocklist/{id}", h.arrAPI(h.ApiBlocklistDelete))
	mux.HandleFunc("GET /api/v3/history", h.arrAPI(h.ApiHistory))
	mux.HandleFunc("GET /api/v3/qualityprofile", h.arrAPI(h.ApiQualityProfiles))
	mux.HandleFunc("GET /api/v3/rootfolder", h.arrAPI(h.ApiRootFolders))
	mux.HandleFunc("GET /api/v3/downloadclient", h.arrAPI(h.ApiDownloadClients))
	mux.HandleFunc("GET /api/v3/health", h.arrAPI(h.ApiHealth))
	mux.HandleFunc("GET /api/v3/command", h.arrAPI(h.ApiCommands))
	mux.HandleFunc("POST /api/v3/command", h.arrAPI(h.ApiCommand))
	mux.HandleFunc("GET /settings/indexers/{id}/edit", h.EditIndexerForm)
	mux.HandleFunc("POST /settings/indexers/{id}", h.UpdateIndexer)
	mux.HandleFunc("DELETE /settings/indexers/{id}", h.DeleteIndexer)
	mux.HandleFunc("GET /settings/download-clients/new", h.NewDownloadClientForm)
	mux.HandleFunc("POST /settings/download-clients", h.CreateDownloadClient)
	mux.HandleFunc("POST /settings/download-clients/test", h.TestDownloadClient)
	mux.HandleFunc("POST /settings/download-handling", h.UpdateDownloadHandling)
	mux.HandleFunc("GET /settings/download-clients/{id}/edit", h.EditDownloadClientForm)
	mux.HandleFunc("POST /settings/download-clients/{id}", h.UpdateDownloadClient)
	mux.HandleFunc("DELETE /settings/download-clients/{id}", h.DeleteDownloadClient)
	mux.HandleFunc("GET /settings/notifications/new", h.NewNotificationForm)
	mux.HandleFunc("POST /settings/notifications", h.CreateNotification)
	mux.HandleFunc("POST /settings/notifications/test", h.TestNotification)
	mux.HandleFunc("GET /settings/notifications/{id}/edit", h.EditNotificationForm)
	mux.HandleFunc("POST /settings/notifications/{id}", h.UpdateNotification)
	mux.HandleFunc("DELETE /settings/notifications/{id}", h.DeleteNotification)
	mux.HandleFunc("POST /settings/media-management", h.UpdateMediaManagement)
	mux.HandleFunc("POST /settings/scan-library", h.ScanLibrary)
	mux.HandleFunc("GET /calendar", h.Calendar)
	mux.HandleFunc("GET /library/scan-report", h.ScanReport)
	mux.HandleFunc("GET /library/scan-report/{id}/match", h.ScanReportMatch)
	mux.HandleFunc("POST /library/scan-report/{id}/match", h.ScanReportMatchApply)
	mux.HandleFunc("POST /library/scan-report/{id}/ignore", h.ScanReportIgnore)
	mux.HandleFunc("POST /library/scan-report/{id}/dismiss", h.ScanReportDismiss)
	mux.HandleFunc("GET /settings/scan-library/status", h.LibraryImportStatus)

	return h.requireAuth(mux)
}
